// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZScMqlIdqjiQlyXETq0_xC6KpAcC_8zc',
    appId: '1:804764591308:web:1316e531e14a00218f4e69',
    messagingSenderId: '804764591308',
    projectId: 'crud-2308b2',
    authDomain: 'crud-2308b2.firebaseapp.com',
    storageBucket: 'crud-2308b2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByuIjgiTckD-NmECJQQpWFN0MGkooxF7k',
    appId: '1:804764591308:android:73934baf9dcfa8bf8f4e69',
    messagingSenderId: '804764591308',
    projectId: 'crud-2308b2',
    storageBucket: 'crud-2308b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxbgJOBjkmIp15dpxqa9pfuhZ9P0qHi2w',
    appId: '1:804764591308:ios:ac89290fc031d72e8f4e69',
    messagingSenderId: '804764591308',
    projectId: 'crud-2308b2',
    storageBucket: 'crud-2308b2.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );
}
